# -*- coding: utf-8 -*-
"""aula2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10zZDQ27OsQT5GYgx1jc3mEEFemfcSyXd
"""

numero = 28

# comentário
# variaveis do tipo caractere:
# greeting = input ('Digite um cumprimento: ')
# name = input ('Digite seu nome: ')
# print(greeting, "Alex")


#variaveis do tipo lógico
# escolha = True
# escolha2 = False
# escolha = False
# escolha2 = True

# NUMERO = 20

# print(escolha)
# print(escolha2)
# print(NUMERO)

#Convenções *snake_case *camelCase
#Convenção Python = snake_case

# user_name = 'Alex'
# casa_grande = "House"

#----------------------------------------Exercícios---------------

# 1 - CRIE UM SISTEMA QUE SOME 2 NUMEROS
n1 = int(input("Digite o primeiro valor: "))
n2 = int(input('Digite o segundo valor: '))
print('A soma dos valores é: ',n1+n2)

# 2 - CRIE UM SISTEMA QUE IMPRIMA SEU NOME NA TELA
nome2 = input('Digite seu nome: ')
print('Seu nome é:',nome2)

# 3 - CRIE UM SISTEMA QUE IMPRIMA SEU NOME E UM CUMPRIMENTO APÓS NOME(CONCATENE)
primeiro_nome = input('Digite seu nome:')
saudacao_cumprimento = input('Digite um cumprime1nto:')
print(primeiro_nome+',', saudacao_cumprimento)

# 4 - CRIE UM SISTEMA QUE MULTIPLIQUE 2 NÚMEROS

n3 = int(input('Digite o primeiro número: '))
n4 = int(input('Digite o segundo número: '))
print('A multiplicação dos números é: ',n3*n4)

